### ISSUE TITLE
سلام وقتتون بخیر ببخشید میشه دیتاستتون رو به من هم معرفی کنید کارم خیلی واجبه لطفا کمکم کنید

### ISSUE THREAD

**Issue by End14e** [reza1615/PersianOcr#14]
سلام وقتتون بخیر ببخشید میشه دیتاستتون رو به من هم معرفی کنید کارم خیلی واجبه لطفا کمکم کنید

_Originally posted by @Erm14 in https://github.com/reza1615/PersianOcr/issues/5#issuecomment-616330999_

**Comment by EsiKhoob** [comment]
سلام

وقت شما هم بخیر

کار بقیه واجب نیست؟

فایلها و فولدر های مربوط به tesseract من در فایل پیوست موجود است، نمی‌دانم کدام یکی را میخواهید؟ 

این لیست با دستور  dir /s ایجاد کرده ام.
