### ISSUE TITLE
چرا Github?

### ISSUE THREAD

**Issue by EsiKhoob** [reza1615/PersianOcr#3]
<div dir="rtl">
با سلام
چرا برنامه  زبان فارسی را روی سایتی گذاشته اید که از ایران نمی شود راحت کار کرد (منظور Github)؟
من حاضر نیستم برای خدمت به خلق الله و توسعه یک برنامه اوپن سورس ، از فیلتر شکن استفاده کنم.
آیا امکان جابجایی این پروژه به سایتهای بهتر هست؟ 

از زحمات شما ممنون.

**Comment by ebraminio** [comment]
<div dir="rtl">
یه اشکالایی داره ولی تاحالا نشنیدم/ندیدم که سایت اصلیش فیلتر یا مشکلات مشابه داشته باشه. بخواید اینجوری حساب کنید هر سایتی مشکل داره، sourceforge که به ایرانی‌ها بی‌احترامی می‌کنه، code.google.com که سایت اصلیش بستس و سایت‌های دیگه هم (مثلاً bitbucket) اگه بخواید از https استفاده کنید همین مشکل‌ها رو دارن...<br />
به هر حال فعلاً که خبری در این پروژه نیست اگه هم این پروژه به محصولی رسید در سایت دیگه‌ای هم منتشر خواهد شد.<br />
باگ رو با اجازه می‌بندم چون راستش بنظرم این باگ نیست ولی اگه شما یا رضا یا هر کسی خواست نظری بده مشکلی نیست :)
</div>

**Comment by EsiKhoob** [comment]
<div dir="rtl">
چون با اون دکمه بالا که روش zip نوشته شده نمیشد دانلود کرد (بدون هیچ پیغامی) من فکر کردم که سایتش ایران را تحریم کرده.
نگو شما مجوز نداده بودید ، . . .  که الان دادید.

**Comment by ebraminio** [comment]
<div dir="rtl">
من فکر می‌کنم چون حجم فایل‌های این پروژه خیلی بزرگ شده، درست‌کردن زیپ خیلی طولانی میشه و دفعهٔ اولی که درخواست زیپ داده می‌شده خیلی طول  می‌کشه ولی دفعه‌های بعد چون زیپ آمده شده راحت قابل دانلوده
</div>
